spring:
  application:
    name: user-center
  #Database Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc::mysql://localhost:3306/
    username: root
    password: 20020901lcb
server:
  port: 8101
# 解决mybatis 驼峰转下划线
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
